# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build dotnet package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish --no-restore --configuration Release -o "test_rel"
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal
    - name: Pack files
      run: 7z a -tzip "test_release.zip" "./test_rel/*"
    - name: Delete output directory
      run: rm -r "test_rel"

    - name: Publish
      uses: softprops/action-gh-release@v1
      with:
        files: "test_release.zip"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}